spring.application.name=vault


spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}
server.port=${PORT:8080}


#executes if there is any update in DDLs
spring.jpa.hibernate.ddl-auto=update


#for logging all sql
logging.level.org.hibernate.SQL=debug
logging.level.org.hibernate.orm.jdbc.bind=trace

